apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mycontainer
    image: nginx
    volumeMounts:  # Определение мест примонтированных томов
    - name: myvolume  # Имя тома
      mountPath: /usr/share/nginx/html  # Путь, куда будет примонтирован том в контейнере
  volumes:  # Определение томов
  - name: myvolume  # Имя тома
    emptyDir: {}  # Пустой том, который будет создан при создании пода
