apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  username: YWRtaW4=  # Закодированное значение "admin"
  password: MWYyZDFlMmU2N2Rm  # Закодированное значение "1f2d1e2e67df"
