apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mycontainer
    image: nginx
    resources:
      requests:
        memory: "64Mi"  # Минимальное количество памяти, необходимое для пода
        cpu: "250m"     # Минимальная доля CPU, необходимая для пода
      limits:
        memory: "128Mi" # Максимальное количество памяти, доступное для пода
        cpu: "500m"     # Максимальная доля CPU, доступная для пода
