apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mycontainer
    image: nginx
    readinessProbe:
      httpGet:
        path: /healthz
        port: 80
      initialDelaySeconds: 5    # Подождать 5 секунд перед началом проверки
      periodSeconds: 10         # Проверять готовность каждые 10 секунд
      timeoutSeconds: 5         # Ожидать ответа не более 5 секунд
      successThreshold: 1       # Считать проверку успешной после 1 успешного ответа
      failureThreshold: 3       # Считать проверку неуспешной после 3 неуспешных ответов
